version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    healthcheck:
      test: "mysql -u${MYSQLDB_USER} -p${MYSQLDB_ROOT_PASSWORD} ${MYSQLDB_DATABASE}"
      interval: 5s
      timeout: 1s
      retries: 20
  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: football-manager-api
    build: ./football-manager-api/.
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "db.url" : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC",
        "db.driver" : "com.mysql.cj.jdbc.Driver",
        "db.user" : "${MYSQLDB_USER}",
        "db.password" : "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
  frontend:
    image: football-manager-frontend
    build: ./frontend/.
    ports:
      - ${ANGULAR_LOCAL_PORT}:${ANGULAR_DOCKER_PORT}
    depends_on:
      - backend
